<?php

/**
 * Implementation of hook_uuid_features_default_terms().
 */
function fe_default_content_uuid_features_default_terms() {
  $terms = array();

  $terms[] = array(
    'uuid' => '05f6b2f3-7636-11e0-ad89-c44619ee2e3d',
    'name' => 'Albums',
    'description' => '',
    'weight' => '0',
    'uuid_vocabulary' => '05f5f602-7636-11e0-ad89-c44619ee2e3d',
  );
  $terms[] = array(
    'uuid' => '3b05805e-7671-11e0-ad89-c44619ee2e3d',
    'name' => 'Lyrics ',
    'description' => '',
    'weight' => '0',
    'uuid_vocabulary' => '05f5f602-7636-11e0-ad89-c44619ee2e3d',
  );
  $terms[] = array(
    'uuid' => 'ea79ffa6-7672-11e0-ad89-c44619ee2e3d',
    'name' => 'Beats ',
    'description' => '',
    'weight' => '0',
    'uuid_vocabulary' => '05f5f602-7636-11e0-ad89-c44619ee2e3d',
  );
  $terms[] = array(
    'uuid' => 'ea7aa056-7672-11e0-ad89-c44619ee2e3d',
    'name' => 'Harmony ',
    'description' => '',
    'weight' => '0',
    'uuid_vocabulary' => '05f5f602-7636-11e0-ad89-c44619ee2e3d',
  );
  $terms[] = array(
    'uuid' => 'ea7b2795-7672-11e0-ad89-c44619ee2e3d',
    'name' => 'Instruments',
    'description' => '',
    'weight' => '0',
    'uuid_vocabulary' => '05f5f602-7636-11e0-ad89-c44619ee2e3d',
  );
  $terms[] = array(
    'uuid' => 'ea7be46f-7672-11e0-ad89-c44619ee2e3d',
    'name' => 'Live shows',
    'description' => '',
    'weight' => '0',
    'uuid_vocabulary' => '05f5f602-7636-11e0-ad89-c44619ee2e3d',
  );
  $terms[] = array(
    'uuid' => 'ea7c78f4-7672-11e0-ad89-c44619ee2e3d',
    'name' => 'Melody',
    'description' => '',
    'weight' => '0',
    'uuid_vocabulary' => '05f5f602-7636-11e0-ad89-c44619ee2e3d',
  );
  $terms[] = array(
    'uuid' => 'ea7d227c-7672-11e0-ad89-c44619ee2e3d',
    'name' => 'Productions',
    'description' => '',
    'weight' => '0',
    'uuid_vocabulary' => '05f5f602-7636-11e0-ad89-c44619ee2e3d',
  );
  $terms[] = array(
    'uuid' => 'ea7dbd04-7672-11e0-ad89-c44619ee2e3d',
    'name' => 'Songs',
    'description' => '',
    'weight' => '0',
    'uuid_vocabulary' => '05f5f602-7636-11e0-ad89-c44619ee2e3d',
  );
  $terms[] = array(
    'uuid' => 'ea7e2d1b-7672-11e0-ad89-c44619ee2e3d',
    'name' => 'Studio',
    'description' => '',
    'weight' => '0',
    'uuid_vocabulary' => '05f5f602-7636-11e0-ad89-c44619ee2e3d',
  );
  return $terms;
}
