<?php

/**
 * Implementation of hook_content_default_fields().
 */
function main_content_default_fields() {
  $fields = array();

  // Exported field: field_in_action
  $fields['idea-field_in_action'] = array(
    'field_name' => 'field_in_action',
    'type_name' => 'idea',
    'display_settings' => array(
      'label' => array(
        'format' => 'above',
        'exclude' => 0,
      ),
      'teaser' => array(
        'format' => 'default',
        'exclude' => 0,
      ),
      'full' => array(
        'format' => 'default',
        'exclude' => 0,
      ),
      '4' => array(
        'format' => 'default',
        'exclude' => 0,
      ),
      '2' => array(
        'format' => 'default',
        'exclude' => 0,
      ),
      '3' => array(
        'format' => 'default',
        'exclude' => 0,
      ),
      'token' => array(
        'format' => 'default',
        'exclude' => 0,
      ),
    ),
    'widget_active' => '1',
    'type' => 'text',
    'required' => '0',
    'multiple' => '0',
    'module' => 'text',
    'active' => '1',
    'text_processing' => '0',
    'max_length' => '',
    'allowed_values' => '',
    'allowed_values_php' => 'return array(
\'Under Review\' => t(\'Under Review\'),
\'Reviewed\' => t(\'Reviewed\'),
\'Coming Soon\' => t(\'Coming Soon\'),
\'Launched\' => t(\'Launched\'),
);',
    'widget' => array(
      'default_value' => array(
        '0' => array(
          'value' => '',
        ),
      ),
      'default_value_php' => NULL,
      'label' => 'In Action',
      'weight' => '-7',
      'description' => '',
      'type' => 'optionwidgets_buttons',
      'module' => 'optionwidgets',
    ),
  );

  // Translatables
  // Included for use with string extractors like potx.
  t('In Action');

  return $fields;
}
